insert into provinces (`id`,`name`) values ('1','Bali');
insert into provinces (`id`,`name`) values ('2','Bangka Belitung');
insert into provinces (`id`,`name`) values ('3','Banten');
insert into provinces (`id`,`name`) values ('4','Bengkulu');
insert into provinces (`id`,`name`) values ('5','DI Yogyakarta');
insert into provinces (`id`,`name`) values ('6','DKI Jakarta');
insert into provinces (`id`,`name`) values ('7','Gorontalo');
insert into provinces (`id`,`name`) values ('8','Jambi');
insert into provinces (`id`,`name`) values ('9','Jawa Barat');
insert into provinces (`id`,`name`) values ('10','Jawa Tengah');
insert into provinces (`id`,`name`) values ('11','Jawa Timur');
insert into provinces (`id`,`name`) values ('12','Kalimantan Barat');
insert into provinces (`id`,`name`) values ('13','Kalimantan Selatan');
insert into provinces (`id`,`name`) values ('14','Kalimantan Tengah');
insert into provinces (`id`,`name`) values ('15','Kalimantan Timur');
insert into provinces (`id`,`name`) values ('16','Kalimantan Utara');
insert into provinces (`id`,`name`) values ('17','Kepulauan Riau');
insert into provinces (`id`,`name`) values ('18','Lampung');
insert into provinces (`id`,`name`) values ('19','Maluku');
insert into provinces (`id`,`name`) values ('20','Maluku Utara');
insert into provinces (`id`,`name`) values ('21','Nanggroe Aceh Darussalam (NAD)');
insert into provinces (`id`,`name`) values ('22','Nusa Tenggara Barat (NTB)');
insert into provinces (`id`,`name`) values ('23','Nusa Tenggara Timur (NTT)');
insert into provinces (`id`,`name`) values ('24','Papua');
insert into provinces (`id`,`name`) values ('25','Papua Barat');
insert into provinces (`id`,`name`) values ('26','Riau');
insert into provinces (`id`,`name`) values ('27','Sulawesi Barat');
insert into provinces (`id`,`name`) values ('28','Sulawesi Selatan');
insert into provinces (`id`,`name`) values ('29','Sulawesi Tengah');
insert into provinces (`id`,`name`) values ('30','Sulawesi Tenggara');
insert into provinces (`id`,`name`) values ('31','Sulawesi Utara');
insert into provinces (`id`,`name`) values ('32','Sumatera Barat');
insert into provinces (`id`,`name`) values ('33','Sumatera Selatan');
insert into provinces (`id`,`name`) values ('34','Sumatera Utara');

insert into cities (`id`,`province_id`,`type`,`name`) values ('1','21','Kabupaten','Aceh Barat');
insert into cities (`id`,`province_id`,`type`,`name`) values ('2','21','Kabupaten','Aceh Barat Daya');
insert into cities (`id`,`province_id`,`type`,`name`) values ('3','21','Kabupaten','Aceh Besar');
insert into cities (`id`,`province_id`,`type`,`name`) values ('4','21','Kabupaten','Aceh Jaya');
insert into cities (`id`,`province_id`,`type`,`name`) values ('5','21','Kabupaten','Aceh Selatan');
insert into cities (`id`,`province_id`,`type`,`name`) values ('6','21','Kabupaten','Aceh Singkil');
insert into cities (`id`,`province_id`,`type`,`name`) values ('7','21','Kabupaten','Aceh Tamiang');
insert into cities (`id`,`province_id`,`type`,`name`) values ('8','21','Kabupaten','Aceh Tengah');
insert into cities (`id`,`province_id`,`type`,`name`) values ('9','21','Kabupaten','Aceh Tenggara');
insert into cities (`id`,`province_id`,`type`,`name`) values ('10','21','Kabupaten','Aceh Timur');
insert into cities (`id`,`province_id`,`type`,`name`) values ('11','21','Kabupaten','Aceh Utara');
insert into cities (`id`,`province_id`,`type`,`name`) values ('12','32','Kabupaten','Agam');
insert into cities (`id`,`province_id`,`type`,`name`) values ('13','23','Kabupaten','Alor');
insert into cities (`id`,`province_id`,`type`,`name`) values ('14','19','Kota','Ambon');
insert into cities (`id`,`province_id`,`type`,`name`) values ('15','34','Kabupaten','Asahan');
insert into cities (`id`,`province_id`,`type`,`name`) values ('16','24','Kabupaten','Asmat');
insert into cities (`id`,`province_id`,`type`,`name`) values ('17','1','Kabupaten','Badung');
insert into cities (`id`,`province_id`,`type`,`name`) values ('18','13','Kabupaten','Balangan');
insert into cities (`id`,`province_id`,`type`,`name`) values ('19','15','Kota','Balikpapan');
insert into cities (`id`,`province_id`,`type`,`name`) values ('20','21','Kota','Banda Aceh');
insert into cities (`id`,`province_id`,`type`,`name`) values ('21','18','Kota','Bandar Lampung');
insert into cities (`id`,`province_id`,`type`,`name`) values ('22','9','Kabupaten','Bandung');
insert into cities (`id`,`province_id`,`type`,`name`) values ('23','9','Kota','Bandung');
insert into cities (`id`,`province_id`,`type`,`name`) values ('24','9','Kabupaten','Bandung Barat');
insert into cities (`id`,`province_id`,`type`,`name`) values ('25','29','Kabupaten','Banggai');
insert into cities (`id`,`province_id`,`type`,`name`) values ('26','29','Kabupaten','Banggai Kepulauan');
insert into cities (`id`,`province_id`,`type`,`name`) values ('27','2','Kabupaten','Bangka');
insert into cities (`id`,`province_id`,`type`,`name`) values ('28','2','Kabupaten','Bangka Barat');
insert into cities (`id`,`province_id`,`type`,`name`) values ('29','2','Kabupaten','Bangka Selatan');
insert into cities (`id`,`province_id`,`type`,`name`) values ('30','2','Kabupaten','Bangka Tengah');
insert into cities (`id`,`province_id`,`type`,`name`) values ('31','11','Kabupaten','Bangkalan');
insert into cities (`id`,`province_id`,`type`,`name`) values ('32','1','Kabupaten','Bangli');
insert into cities (`id`,`province_id`,`type`,`name`) values ('33','13','Kabupaten','Banjar');
insert into cities (`id`,`province_id`,`type`,`name`) values ('34','9','Kota','Banjar');
insert into cities (`id`,`province_id`,`type`,`name`) values ('35','13','Kota','Banjarbaru');
insert into cities (`id`,`province_id`,`type`,`name`) values ('36','13','Kota','Banjarmasin');
insert into cities (`id`,`province_id`,`type`,`name`) values ('37','10','Kabupaten','Banjarnegara');
insert into cities (`id`,`province_id`,`type`,`name`) values ('38','28','Kabupaten','Bantaeng');
insert into cities (`id`,`province_id`,`type`,`name`) values ('39','5','Kabupaten','Bantul');
insert into cities (`id`,`province_id`,`type`,`name`) values ('40','33','Kabupaten','Banyuasin');
insert into cities (`id`,`province_id`,`type`,`name`) values ('41','10','Kabupaten','Banyumas');
insert into cities (`id`,`province_id`,`type`,`name`) values ('42','11','Kabupaten','Banyuwangi');
insert into cities (`id`,`province_id`,`type`,`name`) values ('43','13','Kabupaten','Barito Kuala');
insert into cities (`id`,`province_id`,`type`,`name`) values ('44','14','Kabupaten','Barito Selatan');
insert into cities (`id`,`province_id`,`type`,`name`) values ('45','14','Kabupaten','Barito Timur');
insert into cities (`id`,`province_id`,`type`,`name`) values ('46','14','Kabupaten','Barito Utara');
insert into cities (`id`,`province_id`,`type`,`name`) values ('47','28','Kabupaten','Barru');
insert into cities (`id`,`province_id`,`type`,`name`) values ('48','17','Kota','Batam');
insert into cities (`id`,`province_id`,`type`,`name`) values ('49','10','Kabupaten','Batang');
insert into cities (`id`,`province_id`,`type`,`name`) values ('50','8','Kabupaten','Batang Hari');
insert into cities (`id`,`province_id`,`type`,`name`) values ('51','11','Kota','Batu');
insert into cities (`id`,`province_id`,`type`,`name`) values ('52','34','Kabupaten','Batu Bara');
insert into cities (`id`,`province_id`,`type`,`name`) values ('53','30','Kota','Bau-Bau');
insert into cities (`id`,`province_id`,`type`,`name`) values ('54','9','Kabupaten','Bekasi');
insert into cities (`id`,`province_id`,`type`,`name`) values ('55','9','Kota','Bekasi');
insert into cities (`id`,`province_id`,`type`,`name`) values ('56','2','Kabupaten','Belitung');
insert into cities (`id`,`province_id`,`type`,`name`) values ('57','2','Kabupaten','Belitung Timur');
insert into cities (`id`,`province_id`,`type`,`name`) values ('58','23','Kabupaten','Belu');
insert into cities (`id`,`province_id`,`type`,`name`) values ('59','21','Kabupaten','Bener Meriah');
insert into cities (`id`,`province_id`,`type`,`name`) values ('60','26','Kabupaten','Bengkalis');
insert into cities (`id`,`province_id`,`type`,`name`) values ('61','12','Kabupaten','Bengkayang');
insert into cities (`id`,`province_id`,`type`,`name`) values ('62','4','Kota','Bengkulu');
insert into cities (`id`,`province_id`,`type`,`name`) values ('63','4','Kabupaten','Bengkulu Selatan');
insert into cities (`id`,`province_id`,`type`,`name`) values ('64','4','Kabupaten','Bengkulu Tengah');
insert into cities (`id`,`province_id`,`type`,`name`) values ('65','4','Kabupaten','Bengkulu Utara');
insert into cities (`id`,`province_id`,`type`,`name`) values ('66','15','Kabupaten','Berau');
insert into cities (`id`,`province_id`,`type`,`name`) values ('67','24','Kabupaten','Biak Numfor');
insert into cities (`id`,`province_id`,`type`,`name`) values ('68','22','Kabupaten','Bima');
insert into cities (`id`,`province_id`,`type`,`name`) values ('69','22','Kota','Bima');
insert into cities (`id`,`province_id`,`type`,`name`) values ('70','34','Kota','Binjai');
insert into cities (`id`,`province_id`,`type`,`name`) values ('71','17','Kabupaten','Bintan');
insert into cities (`id`,`province_id`,`type`,`name`) values ('72','21','Kabupaten','Bireuen');
insert into cities (`id`,`province_id`,`type`,`name`) values ('73','31','Kota','Bitung');
insert into cities (`id`,`province_id`,`type`,`name`) values ('74','11','Kabupaten','Blitar');
insert into cities (`id`,`province_id`,`type`,`name`) values ('75','11','Kota','Blitar');
insert into cities (`id`,`province_id`,`type`,`name`) values ('76','10','Kabupaten','Blora');
insert into cities (`id`,`province_id`,`type`,`name`) values ('77','7','Kabupaten','Boalemo');
insert into cities (`id`,`province_id`,`type`,`name`) values ('78','9','Kabupaten','Bogor');
insert into cities (`id`,`province_id`,`type`,`name`) values ('79','9','Kota','Bogor');
insert into cities (`id`,`province_id`,`type`,`name`) values ('80','11','Kabupaten','Bojonegoro');
insert into cities (`id`,`province_id`,`type`,`name`) values ('81','31','Kabupaten','Bolaang Mongondow (Bolmong)');
insert into cities (`id`,`province_id`,`type`,`name`) values ('82','31','Kabupaten','Bolaang Mongondow Selatan');
insert into cities (`id`,`province_id`,`type`,`name`) values ('83','31','Kabupaten','Bolaang Mongondow Timur');
insert into cities (`id`,`province_id`,`type`,`name`) values ('84','31','Kabupaten','Bolaang Mongondow Utara');
insert into cities (`id`,`province_id`,`type`,`name`) values ('85','30','Kabupaten','Bombana');
insert into cities (`id`,`province_id`,`type`,`name`) values ('86','11','Kabupaten','Bondowoso');
insert into cities (`id`,`province_id`,`type`,`name`) values ('87','28','Kabupaten','Bone');
insert into cities (`id`,`province_id`,`type`,`name`) values ('88','7','Kabupaten','Bone Bolango');
insert into cities (`id`,`province_id`,`type`,`name`) values ('89','15','Kota','Bontang');
insert into cities (`id`,`province_id`,`type`,`name`) values ('90','24','Kabupaten','Boven Digoel');
insert into cities (`id`,`province_id`,`type`,`name`) values ('91','10','Kabupaten','Boyolali');
insert into cities (`id`,`province_id`,`type`,`name`) values ('92','10','Kabupaten','Brebes');
insert into cities (`id`,`province_id`,`type`,`name`) values ('93','32','Kota','Bukittinggi');
insert into cities (`id`,`province_id`,`type`,`name`) values ('94','1','Kabupaten','Buleleng');
insert into cities (`id`,`province_id`,`type`,`name`) values ('95','28','Kabupaten','Bulukumba');
insert into cities (`id`,`province_id`,`type`,`name`) values ('96','16','Kabupaten','Bulungan (Bulongan)');
insert into cities (`id`,`province_id`,`type`,`name`) values ('97','8','Kabupaten','Bungo');
insert into cities (`id`,`province_id`,`type`,`name`) values ('98','29','Kabupaten','Buol');
insert into cities (`id`,`province_id`,`type`,`name`) values ('99','19','Kabupaten','Buru');
insert into cities (`id`,`province_id`,`type`,`name`) values ('100','19','Kabupaten','Buru Selatan');
insert into cities (`id`,`province_id`,`type`,`name`) values ('101','30','Kabupaten','Buton');
insert into cities (`id`,`province_id`,`type`,`name`) values ('102','30','Kabupaten','Buton Utara');
insert into cities (`id`,`province_id`,`type`,`name`) values ('103','9','Kabupaten','Ciamis');
insert into cities (`id`,`province_id`,`type`,`name`) values ('104','9','Kabupaten','Cianjur');
insert into cities (`id`,`province_id`,`type`,`name`) values ('105','10','Kabupaten','Cilacap');
insert into cities (`id`,`province_id`,`type`,`name`) values ('106','3','Kota','Cilegon');
insert into cities (`id`,`province_id`,`type`,`name`) values ('107','9','Kota','Cimahi');
insert into cities (`id`,`province_id`,`type`,`name`) values ('108','9','Kabupaten','Cirebon');
insert into cities (`id`,`province_id`,`type`,`name`) values ('109','9','Kota','Cirebon');
insert into cities (`id`,`province_id`,`type`,`name`) values ('110','34','Kabupaten','Dairi');
insert into cities (`id`,`province_id`,`type`,`name`) values ('111','24','Kabupaten','Deiyai (Deliyai)');
insert into cities (`id`,`province_id`,`type`,`name`) values ('112','34','Kabupaten','Deli Serdang');
insert into cities (`id`,`province_id`,`type`,`name`) values ('113','10','Kabupaten','Demak');
insert into cities (`id`,`province_id`,`type`,`name`) values ('114','1','Kota','Denpasar');
insert into cities (`id`,`province_id`,`type`,`name`) values ('115','9','Kota','Depok');
insert into cities (`id`,`province_id`,`type`,`name`) values ('116','32','Kabupaten','Dharmasraya');
insert into cities (`id`,`province_id`,`type`,`name`) values ('117','24','Kabupaten','Dogiyai');
insert into cities (`id`,`province_id`,`type`,`name`) values ('118','22','Kabupaten','Dompu');
insert into cities (`id`,`province_id`,`type`,`name`) values ('119','29','Kabupaten','Donggala');
insert into cities (`id`,`province_id`,`type`,`name`) values ('120','26','Kota','Dumai');
insert into cities (`id`,`province_id`,`type`,`name`) values ('121','33','Kabupaten','Empat Lawang');
insert into cities (`id`,`province_id`,`type`,`name`) values ('122','23','Kabupaten','Ende');
insert into cities (`id`,`province_id`,`type`,`name`) values ('123','28','Kabupaten','Enrekang');
insert into cities (`id`,`province_id`,`type`,`name`) values ('124','25','Kabupaten','Fakfak');
insert into cities (`id`,`province_id`,`type`,`name`) values ('125','23','Kabupaten','Flores Timur');
insert into cities (`id`,`province_id`,`type`,`name`) values ('126','9','Kabupaten','Garut');
insert into cities (`id`,`province_id`,`type`,`name`) values ('127','21','Kabupaten','Gayo Lues');
insert into cities (`id`,`province_id`,`type`,`name`) values ('128','1','Kabupaten','Gianyar');
insert into cities (`id`,`province_id`,`type`,`name`) values ('129','7','Kabupaten','Gorontalo');
insert into cities (`id`,`province_id`,`type`,`name`) values ('130','7','Kota','Gorontalo');
insert into cities (`id`,`province_id`,`type`,`name`) values ('131','7','Kabupaten','Gorontalo Utara');
insert into cities (`id`,`province_id`,`type`,`name`) values ('132','28','Kabupaten','Gowa');
insert into cities (`id`,`province_id`,`type`,`name`) values ('133','11','Kabupaten','Gresik');
insert into cities (`id`,`province_id`,`type`,`name`) values ('134','10','Kabupaten','Grobogan');
insert into cities (`id`,`province_id`,`type`,`name`) values ('135','5','Kabupaten','Gunung Kidul');
insert into cities (`id`,`province_id`,`type`,`name`) values ('136','14','Kabupaten','Gunung Mas');
insert into cities (`id`,`province_id`,`type`,`name`) values ('137','34','Kota','Gunungsitoli');
insert into cities (`id`,`province_id`,`type`,`name`) values ('138','20','Kabupaten','Halmahera Barat');
insert into cities (`id`,`province_id`,`type`,`name`) values ('139','20','Kabupaten','Halmahera Selatan');
insert into cities (`id`,`province_id`,`type`,`name`) values ('140','20','Kabupaten','Halmahera Tengah');
insert into cities (`id`,`province_id`,`type`,`name`) values ('141','20','Kabupaten','Halmahera Timur');
insert into cities (`id`,`province_id`,`type`,`name`) values ('142','20','Kabupaten','Halmahera Utara');
insert into cities (`id`,`province_id`,`type`,`name`) values ('143','13','Kabupaten','Hulu Sungai Selatan');
insert into cities (`id`,`province_id`,`type`,`name`) values ('144','13','Kabupaten','Hulu Sungai Tengah');
insert into cities (`id`,`province_id`,`type`,`name`) values ('145','13','Kabupaten','Hulu Sungai Utara');
insert into cities (`id`,`province_id`,`type`,`name`) values ('146','34','Kabupaten','Humbang Hasundutan');
insert into cities (`id`,`province_id`,`type`,`name`) values ('147','26','Kabupaten','Indragiri Hilir');
insert into cities (`id`,`province_id`,`type`,`name`) values ('148','26','Kabupaten','Indragiri Hulu');
insert into cities (`id`,`province_id`,`type`,`name`) values ('149','9','Kabupaten','Indramayu');
insert into cities (`id`,`province_id`,`type`,`name`) values ('150','24','Kabupaten','Intan Jaya');
insert into cities (`id`,`province_id`,`type`,`name`) values ('151','6','Kota','Jakarta Barat');
insert into cities (`id`,`province_id`,`type`,`name`) values ('152','6','Kota','Jakarta Pusat');
insert into cities (`id`,`province_id`,`type`,`name`) values ('153','6','Kota','Jakarta Selatan');
insert into cities (`id`,`province_id`,`type`,`name`) values ('154','6','Kota','Jakarta Timur');
insert into cities (`id`,`province_id`,`type`,`name`) values ('155','6','Kota','Jakarta Utara');
insert into cities (`id`,`province_id`,`type`,`name`) values ('156','8','Kota','Jambi');
insert into cities (`id`,`province_id`,`type`,`name`) values ('157','24','Kabupaten','Jayapura');
insert into cities (`id`,`province_id`,`type`,`name`) values ('158','24','Kota','Jayapura');
insert into cities (`id`,`province_id`,`type`,`name`) values ('159','24','Kabupaten','Jayawijaya');
insert into cities (`id`,`province_id`,`type`,`name`) values ('160','11','Kabupaten','Jember');
insert into cities (`id`,`province_id`,`type`,`name`) values ('161','1','Kabupaten','Jembrana');
insert into cities (`id`,`province_id`,`type`,`name`) values ('162','28','Kabupaten','Jeneponto');
insert into cities (`id`,`province_id`,`type`,`name`) values ('163','10','Kabupaten','Jepara');
insert into cities (`id`,`province_id`,`type`,`name`) values ('164','11','Kabupaten','Jombang');
insert into cities (`id`,`province_id`,`type`,`name`) values ('165','25','Kabupaten','Kaimana');
insert into cities (`id`,`province_id`,`type`,`name`) values ('166','26','Kabupaten','Kampar');
insert into cities (`id`,`province_id`,`type`,`name`) values ('167','14','Kabupaten','Kapuas');
insert into cities (`id`,`province_id`,`type`,`name`) values ('168','12','Kabupaten','Kapuas Hulu');
insert into cities (`id`,`province_id`,`type`,`name`) values ('169','10','Kabupaten','Karanganyar');
insert into cities (`id`,`province_id`,`type`,`name`) values ('170','1','Kabupaten','Karangasem');
insert into cities (`id`,`province_id`,`type`,`name`) values ('171','9','Kabupaten','Karawang');
insert into cities (`id`,`province_id`,`type`,`name`) values ('172','17','Kabupaten','Karimun');
insert into cities (`id`,`province_id`,`type`,`name`) values ('173','34','Kabupaten','Karo');
insert into cities (`id`,`province_id`,`type`,`name`) values ('174','14','Kabupaten','Katingan');
insert into cities (`id`,`province_id`,`type`,`name`) values ('175','4','Kabupaten','Kaur');
insert into cities (`id`,`province_id`,`type`,`name`) values ('176','12','Kabupaten','Kayong Utara');
insert into cities (`id`,`province_id`,`type`,`name`) values ('177','10','Kabupaten','Kebumen');
insert into cities (`id`,`province_id`,`type`,`name`) values ('178','11','Kabupaten','Kediri');
insert into cities (`id`,`province_id`,`type`,`name`) values ('179','11','Kota','Kediri');
insert into cities (`id`,`province_id`,`type`,`name`) values ('180','24','Kabupaten','Keerom');
insert into cities (`id`,`province_id`,`type`,`name`) values ('181','10','Kabupaten','Kendal');
insert into cities (`id`,`province_id`,`type`,`name`) values ('182','30','Kota','Kendari');
insert into cities (`id`,`province_id`,`type`,`name`) values ('183','4','Kabupaten','Kepahiang');
insert into cities (`id`,`province_id`,`type`,`name`) values ('184','17','Kabupaten','Kepulauan Anambas');
insert into cities (`id`,`province_id`,`type`,`name`) values ('185','19','Kabupaten','Kepulauan Aru');
insert into cities (`id`,`province_id`,`type`,`name`) values ('186','32','Kabupaten','Kepulauan Mentawai');
insert into cities (`id`,`province_id`,`type`,`name`) values ('187','26','Kabupaten','Kepulauan Meranti');
insert into cities (`id`,`province_id`,`type`,`name`) values ('188','31','Kabupaten','Kepulauan Sangihe');
insert into cities (`id`,`province_id`,`type`,`name`) values ('189','6','Kabupaten','Kepulauan Seribu');
insert into cities (`id`,`province_id`,`type`,`name`) values ('190','31','Kabupaten','Kepulauan Siau Tagulandang Biaro (Sitaro)');
insert into cities (`id`,`province_id`,`type`,`name`) values ('191','20','Kabupaten','Kepulauan Sula');
insert into cities (`id`,`province_id`,`type`,`name`) values ('192','31','Kabupaten','Kepulauan Talaud');
insert into cities (`id`,`province_id`,`type`,`name`) values ('193','24','Kabupaten','Kepulauan Yapen (Yapen Waropen)');
insert into cities (`id`,`province_id`,`type`,`name`) values ('194','8','Kabupaten','Kerinci');
insert into cities (`id`,`province_id`,`type`,`name`) values ('195','12','Kabupaten','Ketapang');
insert into cities (`id`,`province_id`,`type`,`name`) values ('196','10','Kabupaten','Klaten');
insert into cities (`id`,`province_id`,`type`,`name`) values ('197','1','Kabupaten','Klungkung');
insert into cities (`id`,`province_id`,`type`,`name`) values ('198','30','Kabupaten','Kolaka');
insert into cities (`id`,`province_id`,`type`,`name`) values ('199','30','Kabupaten','Kolaka Utara');
insert into cities (`id`,`province_id`,`type`,`name`) values ('200','30','Kabupaten','Konawe');
insert into cities (`id`,`province_id`,`type`,`name`) values ('201','30','Kabupaten','Konawe Selatan');
insert into cities (`id`,`province_id`,`type`,`name`) values ('202','30','Kabupaten','Konawe Utara');
insert into cities (`id`,`province_id`,`type`,`name`) values ('203','13','Kabupaten','Kotabaru');
insert into cities (`id`,`province_id`,`type`,`name`) values ('204','31','Kota','Kotamobagu');
insert into cities (`id`,`province_id`,`type`,`name`) values ('205','14','Kabupaten','Kotawaringin Barat');
insert into cities (`id`,`province_id`,`type`,`name`) values ('206','14','Kabupaten','Kotawaringin Timur');
insert into cities (`id`,`province_id`,`type`,`name`) values ('207','26','Kabupaten','Kuantan Singingi');
insert into cities (`id`,`province_id`,`type`,`name`) values ('208','12','Kabupaten','Kubu Raya');
insert into cities (`id`,`province_id`,`type`,`name`) values ('209','10','Kabupaten','Kudus');
insert into cities (`id`,`province_id`,`type`,`name`) values ('210','5','Kabupaten','Kulon Progo');
insert into cities (`id`,`province_id`,`type`,`name`) values ('211','9','Kabupaten','Kuningan');
insert into cities (`id`,`province_id`,`type`,`name`) values ('212','23','Kabupaten','Kupang');
insert into cities (`id`,`province_id`,`type`,`name`) values ('213','23','Kota','Kupang');
insert into cities (`id`,`province_id`,`type`,`name`) values ('214','15','Kabupaten','Kutai Barat');
insert into cities (`id`,`province_id`,`type`,`name`) values ('215','15','Kabupaten','Kutai Kartanegara');
insert into cities (`id`,`province_id`,`type`,`name`) values ('216','15','Kabupaten','Kutai Timur');
insert into cities (`id`,`province_id`,`type`,`name`) values ('217','34','Kabupaten','Labuhan Batu');
insert into cities (`id`,`province_id`,`type`,`name`) values ('218','34','Kabupaten','Labuhan Batu Selatan');
insert into cities (`id`,`province_id`,`type`,`name`) values ('219','34','Kabupaten','Labuhan Batu Utara');
insert into cities (`id`,`province_id`,`type`,`name`) values ('220','33','Kabupaten','Lahat');
insert into cities (`id`,`province_id`,`type`,`name`) values ('221','14','Kabupaten','Lamandau');
insert into cities (`id`,`province_id`,`type`,`name`) values ('222','11','Kabupaten','Lamongan');
insert into cities (`id`,`province_id`,`type`,`name`) values ('223','18','Kabupaten','Lampung Barat');
insert into cities (`id`,`province_id`,`type`,`name`) values ('224','18','Kabupaten','Lampung Selatan');
insert into cities (`id`,`province_id`,`type`,`name`) values ('225','18','Kabupaten','Lampung Tengah');
insert into cities (`id`,`province_id`,`type`,`name`) values ('226','18','Kabupaten','Lampung Timur');
insert into cities (`id`,`province_id`,`type`,`name`) values ('227','18','Kabupaten','Lampung Utara');
insert into cities (`id`,`province_id`,`type`,`name`) values ('228','12','Kabupaten','Landak');
insert into cities (`id`,`province_id`,`type`,`name`) values ('229','34','Kabupaten','Langkat');
insert into cities (`id`,`province_id`,`type`,`name`) values ('230','21','Kota','Langsa');
insert into cities (`id`,`province_id`,`type`,`name`) values ('231','24','Kabupaten','Lanny Jaya');
insert into cities (`id`,`province_id`,`type`,`name`) values ('232','3','Kabupaten','Lebak');
insert into cities (`id`,`province_id`,`type`,`name`) values ('233','4','Kabupaten','Lebong');
insert into cities (`id`,`province_id`,`type`,`name`) values ('234','23','Kabupaten','Lembata');
insert into cities (`id`,`province_id`,`type`,`name`) values ('235','21','Kota','Lhokseumawe');
insert into cities (`id`,`province_id`,`type`,`name`) values ('236','32','Kabupaten','Lima Puluh Koto/Kota');
insert into cities (`id`,`province_id`,`type`,`name`) values ('237','17','Kabupaten','Lingga');
insert into cities (`id`,`province_id`,`type`,`name`) values ('238','22','Kabupaten','Lombok Barat');
insert into cities (`id`,`province_id`,`type`,`name`) values ('239','22','Kabupaten','Lombok Tengah');
insert into cities (`id`,`province_id`,`type`,`name`) values ('240','22','Kabupaten','Lombok Timur');
insert into cities (`id`,`province_id`,`type`,`name`) values ('241','22','Kabupaten','Lombok Utara');
insert into cities (`id`,`province_id`,`type`,`name`) values ('242','33','Kota','Lubuk Linggau');
insert into cities (`id`,`province_id`,`type`,`name`) values ('243','11','Kabupaten','Lumajang');
insert into cities (`id`,`province_id`,`type`,`name`) values ('244','28','Kabupaten','Luwu');
insert into cities (`id`,`province_id`,`type`,`name`) values ('245','28','Kabupaten','Luwu Timur');
insert into cities (`id`,`province_id`,`type`,`name`) values ('246','28','Kabupaten','Luwu Utara');
insert into cities (`id`,`province_id`,`type`,`name`) values ('247','11','Kabupaten','Madiun');
insert into cities (`id`,`province_id`,`type`,`name`) values ('248','11','Kota','Madiun');
insert into cities (`id`,`province_id`,`type`,`name`) values ('249','10','Kabupaten','Magelang');
insert into cities (`id`,`province_id`,`type`,`name`) values ('250','10','Kota','Magelang');
insert into cities (`id`,`province_id`,`type`,`name`) values ('251','11','Kabupaten','Magetan');
insert into cities (`id`,`province_id`,`type`,`name`) values ('252','9','Kabupaten','Majalengka');
insert into cities (`id`,`province_id`,`type`,`name`) values ('253','27','Kabupaten','Majene');
insert into cities (`id`,`province_id`,`type`,`name`) values ('254','28','Kota','Makassar');
insert into cities (`id`,`province_id`,`type`,`name`) values ('255','11','Kabupaten','Malang');
insert into cities (`id`,`province_id`,`type`,`name`) values ('256','11','Kota','Malang');
insert into cities (`id`,`province_id`,`type`,`name`) values ('257','16','Kabupaten','Malinau');
insert into cities (`id`,`province_id`,`type`,`name`) values ('258','19','Kabupaten','Maluku Barat Daya');
insert into cities (`id`,`province_id`,`type`,`name`) values ('259','19','Kabupaten','Maluku Tengah');
insert into cities (`id`,`province_id`,`type`,`name`) values ('260','19','Kabupaten','Maluku Tenggara');
insert into cities (`id`,`province_id`,`type`,`name`) values ('261','19','Kabupaten','Maluku Tenggara Barat');
insert into cities (`id`,`province_id`,`type`,`name`) values ('262','27','Kabupaten','Mamasa');
insert into cities (`id`,`province_id`,`type`,`name`) values ('263','24','Kabupaten','Mamberamo Raya');
insert into cities (`id`,`province_id`,`type`,`name`) values ('264','24','Kabupaten','Mamberamo Tengah');
insert into cities (`id`,`province_id`,`type`,`name`) values ('265','27','Kabupaten','Mamuju');
insert into cities (`id`,`province_id`,`type`,`name`) values ('266','27','Kabupaten','Mamuju Utara');
insert into cities (`id`,`province_id`,`type`,`name`) values ('267','31','Kota','Manado');
insert into cities (`id`,`province_id`,`type`,`name`) values ('268','34','Kabupaten','Mandailing Natal');
insert into cities (`id`,`province_id`,`type`,`name`) values ('269','23','Kabupaten','Manggarai');
insert into cities (`id`,`province_id`,`type`,`name`) values ('270','23','Kabupaten','Manggarai Barat');
insert into cities (`id`,`province_id`,`type`,`name`) values ('271','23','Kabupaten','Manggarai Timur');
insert into cities (`id`,`province_id`,`type`,`name`) values ('272','25','Kabupaten','Manokwari');
insert into cities (`id`,`province_id`,`type`,`name`) values ('273','25','Kabupaten','Manokwari Selatan');
insert into cities (`id`,`province_id`,`type`,`name`) values ('274','24','Kabupaten','Mappi');
insert into cities (`id`,`province_id`,`type`,`name`) values ('275','28','Kabupaten','Maros');
insert into cities (`id`,`province_id`,`type`,`name`) values ('276','22','Kota','Mataram');
insert into cities (`id`,`province_id`,`type`,`name`) values ('277','25','Kabupaten','Maybrat');
insert into cities (`id`,`province_id`,`type`,`name`) values ('278','34','Kota','Medan');
insert into cities (`id`,`province_id`,`type`,`name`) values ('279','12','Kabupaten','Melawi');
insert into cities (`id`,`province_id`,`type`,`name`) values ('280','8','Kabupaten','Merangin');
insert into cities (`id`,`province_id`,`type`,`name`) values ('281','24','Kabupaten','Merauke');
insert into cities (`id`,`province_id`,`type`,`name`) values ('282','18','Kabupaten','Mesuji');
insert into cities (`id`,`province_id`,`type`,`name`) values ('283','18','Kota','Metro');
insert into cities (`id`,`province_id`,`type`,`name`) values ('284','24','Kabupaten','Mimika');
insert into cities (`id`,`province_id`,`type`,`name`) values ('285','31','Kabupaten','Minahasa');
insert into cities (`id`,`province_id`,`type`,`name`) values ('286','31','Kabupaten','Minahasa Selatan');
insert into cities (`id`,`province_id`,`type`,`name`) values ('287','31','Kabupaten','Minahasa Tenggara');
insert into cities (`id`,`province_id`,`type`,`name`) values ('288','31','Kabupaten','Minahasa Utara');
insert into cities (`id`,`province_id`,`type`,`name`) values ('289','11','Kabupaten','Mojokerto');
insert into cities (`id`,`province_id`,`type`,`name`) values ('290','11','Kota','Mojokerto');
insert into cities (`id`,`province_id`,`type`,`name`) values ('291','29','Kabupaten','Morowali');
insert into cities (`id`,`province_id`,`type`,`name`) values ('292','33','Kabupaten','Muara Enim');
insert into cities (`id`,`province_id`,`type`,`name`) values ('293','8','Kabupaten','Muaro Jambi');
insert into cities (`id`,`province_id`,`type`,`name`) values ('294','4','Kabupaten','Muko Muko');
insert into cities (`id`,`province_id`,`type`,`name`) values ('295','30','Kabupaten','Muna');
insert into cities (`id`,`province_id`,`type`,`name`) values ('296','14','Kabupaten','Murung Raya');
insert into cities (`id`,`province_id`,`type`,`name`) values ('297','33','Kabupaten','Musi Banyuasin');
insert into cities (`id`,`province_id`,`type`,`name`) values ('298','33','Kabupaten','Musi Rawas');
insert into cities (`id`,`province_id`,`type`,`name`) values ('299','24','Kabupaten','Nabire');
insert into cities (`id`,`province_id`,`type`,`name`) values ('300','21','Kabupaten','Nagan Raya');
insert into cities (`id`,`province_id`,`type`,`name`) values ('301','23','Kabupaten','Nagekeo');
insert into cities (`id`,`province_id`,`type`,`name`) values ('302','17','Kabupaten','Natuna');
insert into cities (`id`,`province_id`,`type`,`name`) values ('303','24','Kabupaten','Nduga');
insert into cities (`id`,`province_id`,`type`,`name`) values ('304','23','Kabupaten','Ngada');
insert into cities (`id`,`province_id`,`type`,`name`) values ('305','11','Kabupaten','Nganjuk');
insert into cities (`id`,`province_id`,`type`,`name`) values ('306','11','Kabupaten','Ngawi');
insert into cities (`id`,`province_id`,`type`,`name`) values ('307','34','Kabupaten','Nias');
insert into cities (`id`,`province_id`,`type`,`name`) values ('308','34','Kabupaten','Nias Barat');
insert into cities (`id`,`province_id`,`type`,`name`) values ('309','34','Kabupaten','Nias Selatan');
insert into cities (`id`,`province_id`,`type`,`name`) values ('310','34','Kabupaten','Nias Utara');
insert into cities (`id`,`province_id`,`type`,`name`) values ('311','16','Kabupaten','Nunukan');
insert into cities (`id`,`province_id`,`type`,`name`) values ('312','33','Kabupaten','Ogan Ilir');
insert into cities (`id`,`province_id`,`type`,`name`) values ('313','33','Kabupaten','Ogan Komering Ilir');
insert into cities (`id`,`province_id`,`type`,`name`) values ('314','33','Kabupaten','Ogan Komering Ulu');
insert into cities (`id`,`province_id`,`type`,`name`) values ('315','33','Kabupaten','Ogan Komering Ulu Selatan');
insert into cities (`id`,`province_id`,`type`,`name`) values ('316','33','Kabupaten','Ogan Komering Ulu Timur');
insert into cities (`id`,`province_id`,`type`,`name`) values ('317','11','Kabupaten','Pacitan');
insert into cities (`id`,`province_id`,`type`,`name`) values ('318','32','Kota','Padang');
insert into cities (`id`,`province_id`,`type`,`name`) values ('319','34','Kabupaten','Padang Lawas');
insert into cities (`id`,`province_id`,`type`,`name`) values ('320','34','Kabupaten','Padang Lawas Utara');
insert into cities (`id`,`province_id`,`type`,`name`) values ('321','32','Kota','Padang Panjang');
insert into cities (`id`,`province_id`,`type`,`name`) values ('322','32','Kabupaten','Padang Pariaman');
insert into cities (`id`,`province_id`,`type`,`name`) values ('323','34','Kota','Padang Sidempuan');
insert into cities (`id`,`province_id`,`type`,`name`) values ('324','33','Kota','Pagar Alam');
insert into cities (`id`,`province_id`,`type`,`name`) values ('325','34','Kabupaten','Pakpak Bharat');
insert into cities (`id`,`province_id`,`type`,`name`) values ('326','14','Kota','Palangka Raya');
insert into cities (`id`,`province_id`,`type`,`name`) values ('327','33','Kota','Palembang');
insert into cities (`id`,`province_id`,`type`,`name`) values ('328','28','Kota','Palopo');
insert into cities (`id`,`province_id`,`type`,`name`) values ('329','29','Kota','Palu');
insert into cities (`id`,`province_id`,`type`,`name`) values ('330','11','Kabupaten','Pamekasan');
insert into cities (`id`,`province_id`,`type`,`name`) values ('331','3','Kabupaten','Pandeglang');
insert into cities (`id`,`province_id`,`type`,`name`) values ('332','9','Kabupaten','Pangandaran');
insert into cities (`id`,`province_id`,`type`,`name`) values ('333','28','Kabupaten','Pangkajene Kepulauan');
insert into cities (`id`,`province_id`,`type`,`name`) values ('334','2','Kota','Pangkal Pinang');
insert into cities (`id`,`province_id`,`type`,`name`) values ('335','24','Kabupaten','Paniai');
insert into cities (`id`,`province_id`,`type`,`name`) values ('336','28','Kota','Parepare');
insert into cities (`id`,`province_id`,`type`,`name`) values ('337','32','Kota','Pariaman');
insert into cities (`id`,`province_id`,`type`,`name`) values ('338','29','Kabupaten','Parigi Moutong');
insert into cities (`id`,`province_id`,`type`,`name`) values ('339','32','Kabupaten','Pasaman');
insert into cities (`id`,`province_id`,`type`,`name`) values ('340','32','Kabupaten','Pasaman Barat');
insert into cities (`id`,`province_id`,`type`,`name`) values ('341','15','Kabupaten','Paser');
insert into cities (`id`,`province_id`,`type`,`name`) values ('342','11','Kabupaten','Pasuruan');
insert into cities (`id`,`province_id`,`type`,`name`) values ('343','11','Kota','Pasuruan');
insert into cities (`id`,`province_id`,`type`,`name`) values ('344','10','Kabupaten','Pati');
insert into cities (`id`,`province_id`,`type`,`name`) values ('345','32','Kota','Payakumbuh');
insert into cities (`id`,`province_id`,`type`,`name`) values ('346','25','Kabupaten','Pegunungan Arfak');
insert into cities (`id`,`province_id`,`type`,`name`) values ('347','24','Kabupaten','Pegunungan Bintang');
insert into cities (`id`,`province_id`,`type`,`name`) values ('348','10','Kabupaten','Pekalongan');
insert into cities (`id`,`province_id`,`type`,`name`) values ('349','10','Kota','Pekalongan');
insert into cities (`id`,`province_id`,`type`,`name`) values ('350','26','Kota','Pekanbaru');
insert into cities (`id`,`province_id`,`type`,`name`) values ('351','26','Kabupaten','Pelalawan');
insert into cities (`id`,`province_id`,`type`,`name`) values ('352','10','Kabupaten','Pemalang');
insert into cities (`id`,`province_id`,`type`,`name`) values ('353','34','Kota','Pematang Siantar');
insert into cities (`id`,`province_id`,`type`,`name`) values ('354','15','Kabupaten','Penajam Paser Utara');
insert into cities (`id`,`province_id`,`type`,`name`) values ('355','18','Kabupaten','Pesawaran');
insert into cities (`id`,`province_id`,`type`,`name`) values ('356','18','Kabupaten','Pesisir Barat');
insert into cities (`id`,`province_id`,`type`,`name`) values ('357','32','Kabupaten','Pesisir Selatan');
insert into cities (`id`,`province_id`,`type`,`name`) values ('358','21','Kabupaten','Pidie');
insert into cities (`id`,`province_id`,`type`,`name`) values ('359','21','Kabupaten','Pidie Jaya');
insert into cities (`id`,`province_id`,`type`,`name`) values ('360','28','Kabupaten','Pinrang');
insert into cities (`id`,`province_id`,`type`,`name`) values ('361','7','Kabupaten','Pohuwato');
insert into cities (`id`,`province_id`,`type`,`name`) values ('362','27','Kabupaten','Polewali Mandar');
insert into cities (`id`,`province_id`,`type`,`name`) values ('363','11','Kabupaten','Ponorogo');
insert into cities (`id`,`province_id`,`type`,`name`) values ('364','12','Kabupaten','Pontianak');
insert into cities (`id`,`province_id`,`type`,`name`) values ('365','12','Kota','Pontianak');
insert into cities (`id`,`province_id`,`type`,`name`) values ('366','29','Kabupaten','Poso');
insert into cities (`id`,`province_id`,`type`,`name`) values ('367','33','Kota','Prabumulih');
insert into cities (`id`,`province_id`,`type`,`name`) values ('368','18','Kabupaten','Pringsewu');
insert into cities (`id`,`province_id`,`type`,`name`) values ('369','11','Kabupaten','Probolinggo');
insert into cities (`id`,`province_id`,`type`,`name`) values ('370','11','Kota','Probolinggo');
insert into cities (`id`,`province_id`,`type`,`name`) values ('371','14','Kabupaten','Pulang Pisau');
insert into cities (`id`,`province_id`,`type`,`name`) values ('372','20','Kabupaten','Pulau Morotai');
insert into cities (`id`,`province_id`,`type`,`name`) values ('373','24','Kabupaten','Puncak');
insert into cities (`id`,`province_id`,`type`,`name`) values ('374','24','Kabupaten','Puncak Jaya');
insert into cities (`id`,`province_id`,`type`,`name`) values ('375','10','Kabupaten','Purbalingga');
insert into cities (`id`,`province_id`,`type`,`name`) values ('376','9','Kabupaten','Purwakarta');
insert into cities (`id`,`province_id`,`type`,`name`) values ('377','10','Kabupaten','Purworejo');
insert into cities (`id`,`province_id`,`type`,`name`) values ('378','25','Kabupaten','Raja Ampat');
insert into cities (`id`,`province_id`,`type`,`name`) values ('379','4','Kabupaten','Rejang Lebong');
insert into cities (`id`,`province_id`,`type`,`name`) values ('380','10','Kabupaten','Rembang');
insert into cities (`id`,`province_id`,`type`,`name`) values ('381','26','Kabupaten','Rokan Hilir');
insert into cities (`id`,`province_id`,`type`,`name`) values ('382','26','Kabupaten','Rokan Hulu');
insert into cities (`id`,`province_id`,`type`,`name`) values ('383','23','Kabupaten','Rote Ndao');
insert into cities (`id`,`province_id`,`type`,`name`) values ('384','21','Kota','Sabang');
insert into cities (`id`,`province_id`,`type`,`name`) values ('385','23','Kabupaten','Sabu Raijua');
insert into cities (`id`,`province_id`,`type`,`name`) values ('386','10','Kota','Salatiga');
insert into cities (`id`,`province_id`,`type`,`name`) values ('387','15','Kota','Samarinda');
insert into cities (`id`,`province_id`,`type`,`name`) values ('388','12','Kabupaten','Sambas');
insert into cities (`id`,`province_id`,`type`,`name`) values ('389','34','Kabupaten','Samosir');
insert into cities (`id`,`province_id`,`type`,`name`) values ('390','11','Kabupaten','Sampang');
insert into cities (`id`,`province_id`,`type`,`name`) values ('391','12','Kabupaten','Sanggau');
insert into cities (`id`,`province_id`,`type`,`name`) values ('392','24','Kabupaten','Sarmi');
insert into cities (`id`,`province_id`,`type`,`name`) values ('393','8','Kabupaten','Sarolangun');
insert into cities (`id`,`province_id`,`type`,`name`) values ('394','32','Kota','Sawah Lunto');
insert into cities (`id`,`province_id`,`type`,`name`) values ('395','12','Kabupaten','Sekadau');
insert into cities (`id`,`province_id`,`type`,`name`) values ('396','28','Kabupaten','Selayar (Kepulauan Selayar)');
insert into cities (`id`,`province_id`,`type`,`name`) values ('397','4','Kabupaten','Seluma');
insert into cities (`id`,`province_id`,`type`,`name`) values ('398','10','Kabupaten','Semarang');
insert into cities (`id`,`province_id`,`type`,`name`) values ('399','10','Kota','Semarang');
insert into cities (`id`,`province_id`,`type`,`name`) values ('400','19','Kabupaten','Seram Bagian Barat');
insert into cities (`id`,`province_id`,`type`,`name`) values ('401','19','Kabupaten','Seram Bagian Timur');
insert into cities (`id`,`province_id`,`type`,`name`) values ('402','3','Kabupaten','Serang');
insert into cities (`id`,`province_id`,`type`,`name`) values ('403','3','Kota','Serang');
insert into cities (`id`,`province_id`,`type`,`name`) values ('404','34','Kabupaten','Serdang Bedagai');
insert into cities (`id`,`province_id`,`type`,`name`) values ('405','14','Kabupaten','Seruyan');
insert into cities (`id`,`province_id`,`type`,`name`) values ('406','26','Kabupaten','Siak');
insert into cities (`id`,`province_id`,`type`,`name`) values ('407','34','Kota','Sibolga');
insert into cities (`id`,`province_id`,`type`,`name`) values ('408','28','Kabupaten','Sidenreng Rappang/Rapang');
insert into cities (`id`,`province_id`,`type`,`name`) values ('409','11','Kabupaten','Sidoarjo');
insert into cities (`id`,`province_id`,`type`,`name`) values ('410','29','Kabupaten','Sigi');
insert into cities (`id`,`province_id`,`type`,`name`) values ('411','32','Kabupaten','Sijunjung (Sawah Lunto Sijunjung)');
insert into cities (`id`,`province_id`,`type`,`name`) values ('412','23','Kabupaten','Sikka');
insert into cities (`id`,`province_id`,`type`,`name`) values ('413','34','Kabupaten','Simalungun');
insert into cities (`id`,`province_id`,`type`,`name`) values ('414','21','Kabupaten','Simeulue');
insert into cities (`id`,`province_id`,`type`,`name`) values ('415','12','Kota','Singkawang');
insert into cities (`id`,`province_id`,`type`,`name`) values ('416','28','Kabupaten','Sinjai');
insert into cities (`id`,`province_id`,`type`,`name`) values ('417','12','Kabupaten','Sintang');
insert into cities (`id`,`province_id`,`type`,`name`) values ('418','11','Kabupaten','Situbondo');
insert into cities (`id`,`province_id`,`type`,`name`) values ('419','5','Kabupaten','Sleman');
insert into cities (`id`,`province_id`,`type`,`name`) values ('420','32','Kabupaten','Solok');
insert into cities (`id`,`province_id`,`type`,`name`) values ('421','32','Kota','Solok');
insert into cities (`id`,`province_id`,`type`,`name`) values ('422','32','Kabupaten','Solok Selatan');
insert into cities (`id`,`province_id`,`type`,`name`) values ('423','28','Kabupaten','Soppeng');
insert into cities (`id`,`province_id`,`type`,`name`) values ('424','25','Kabupaten','Sorong');
insert into cities (`id`,`province_id`,`type`,`name`) values ('425','25','Kota','Sorong');
insert into cities (`id`,`province_id`,`type`,`name`) values ('426','25','Kabupaten','Sorong Selatan');
insert into cities (`id`,`province_id`,`type`,`name`) values ('427','10','Kabupaten','Sragen');
insert into cities (`id`,`province_id`,`type`,`name`) values ('428','9','Kabupaten','Subang');
insert into cities (`id`,`province_id`,`type`,`name`) values ('429','21','Kota','Subulussalam');
insert into cities (`id`,`province_id`,`type`,`name`) values ('430','9','Kabupaten','Sukabumi');
insert into cities (`id`,`province_id`,`type`,`name`) values ('431','9','Kota','Sukabumi');
insert into cities (`id`,`province_id`,`type`,`name`) values ('432','14','Kabupaten','Sukamara');
insert into cities (`id`,`province_id`,`type`,`name`) values ('433','10','Kabupaten','Sukoharjo');
insert into cities (`id`,`province_id`,`type`,`name`) values ('434','23','Kabupaten','Sumba Barat');
insert into cities (`id`,`province_id`,`type`,`name`) values ('435','23','Kabupaten','Sumba Barat Daya');
insert into cities (`id`,`province_id`,`type`,`name`) values ('436','23','Kabupaten','Sumba Tengah');
insert into cities (`id`,`province_id`,`type`,`name`) values ('437','23','Kabupaten','Sumba Timur');
insert into cities (`id`,`province_id`,`type`,`name`) values ('438','22','Kabupaten','Sumbawa');
insert into cities (`id`,`province_id`,`type`,`name`) values ('439','22','Kabupaten','Sumbawa Barat');
insert into cities (`id`,`province_id`,`type`,`name`) values ('440','9','Kabupaten','Sumedang');
insert into cities (`id`,`province_id`,`type`,`name`) values ('441','11','Kabupaten','Sumenep');
insert into cities (`id`,`province_id`,`type`,`name`) values ('442','8','Kota','Sungaipenuh');
insert into cities (`id`,`province_id`,`type`,`name`) values ('443','24','Kabupaten','Supiori');
insert into cities (`id`,`province_id`,`type`,`name`) values ('444','11','Kota','Surabaya');
insert into cities (`id`,`province_id`,`type`,`name`) values ('445','10','Kota','Surakarta (Solo)');
insert into cities (`id`,`province_id`,`type`,`name`) values ('446','13','Kabupaten','Tabalong');
insert into cities (`id`,`province_id`,`type`,`name`) values ('447','1','Kabupaten','Tabanan');
insert into cities (`id`,`province_id`,`type`,`name`) values ('448','28','Kabupaten','Takalar');
insert into cities (`id`,`province_id`,`type`,`name`) values ('449','25','Kabupaten','Tambrauw');
insert into cities (`id`,`province_id`,`type`,`name`) values ('450','16','Kabupaten','Tana Tidung');
insert into cities (`id`,`province_id`,`type`,`name`) values ('451','28','Kabupaten','Tana Toraja');
insert into cities (`id`,`province_id`,`type`,`name`) values ('452','13','Kabupaten','Tanah Bumbu');
insert into cities (`id`,`province_id`,`type`,`name`) values ('453','32','Kabupaten','Tanah Datar');
insert into cities (`id`,`province_id`,`type`,`name`) values ('454','13','Kabupaten','Tanah Laut');
insert into cities (`id`,`province_id`,`type`,`name`) values ('455','3','Kabupaten','Tangerang');
insert into cities (`id`,`province_id`,`type`,`name`) values ('456','3','Kota','Tangerang');
insert into cities (`id`,`province_id`,`type`,`name`) values ('457','3','Kota','Tangerang Selatan');
insert into cities (`id`,`province_id`,`type`,`name`) values ('458','18','Kabupaten','Tanggamus');
insert into cities (`id`,`province_id`,`type`,`name`) values ('459','34','Kota','Tanjung Balai');
insert into cities (`id`,`province_id`,`type`,`name`) values ('460','8','Kabupaten','Tanjung Jabung Barat');
insert into cities (`id`,`province_id`,`type`,`name`) values ('461','8','Kabupaten','Tanjung Jabung Timur');
insert into cities (`id`,`province_id`,`type`,`name`) values ('462','17','Kota','Tanjung Pinang');
insert into cities (`id`,`province_id`,`type`,`name`) values ('463','34','Kabupaten','Tapanuli Selatan');
insert into cities (`id`,`province_id`,`type`,`name`) values ('464','34','Kabupaten','Tapanuli Tengah');
insert into cities (`id`,`province_id`,`type`,`name`) values ('465','34','Kabupaten','Tapanuli Utara');
insert into cities (`id`,`province_id`,`type`,`name`) values ('466','13','Kabupaten','Tapin');
insert into cities (`id`,`province_id`,`type`,`name`) values ('467','16','Kota','Tarakan');
insert into cities (`id`,`province_id`,`type`,`name`) values ('468','9','Kabupaten','Tasikmalaya');
insert into cities (`id`,`province_id`,`type`,`name`) values ('469','9','Kota','Tasikmalaya');
insert into cities (`id`,`province_id`,`type`,`name`) values ('470','34','Kota','Tebing Tinggi');
insert into cities (`id`,`province_id`,`type`,`name`) values ('471','8','Kabupaten','Tebo');
insert into cities (`id`,`province_id`,`type`,`name`) values ('472','10','Kabupaten','Tegal');
insert into cities (`id`,`province_id`,`type`,`name`) values ('473','10','Kota','Tegal');
insert into cities (`id`,`province_id`,`type`,`name`) values ('474','25','Kabupaten','Teluk Bintuni');
insert into cities (`id`,`province_id`,`type`,`name`) values ('475','25','Kabupaten','Teluk Wondama');
insert into cities (`id`,`province_id`,`type`,`name`) values ('476','10','Kabupaten','Temanggung');
insert into cities (`id`,`province_id`,`type`,`name`) values ('477','20','Kota','Ternate');
insert into cities (`id`,`province_id`,`type`,`name`) values ('478','20','Kota','Tidore Kepulauan');
insert into cities (`id`,`province_id`,`type`,`name`) values ('479','23','Kabupaten','Timor Tengah Selatan');
insert into cities (`id`,`province_id`,`type`,`name`) values ('480','23','Kabupaten','Timor Tengah Utara');
insert into cities (`id`,`province_id`,`type`,`name`) values ('481','34','Kabupaten','Toba Samosir');
insert into cities (`id`,`province_id`,`type`,`name`) values ('482','29','Kabupaten','Tojo Una-Una');
insert into cities (`id`,`province_id`,`type`,`name`) values ('483','29','Kabupaten','Toli-Toli');
insert into cities (`id`,`province_id`,`type`,`name`) values ('484','24','Kabupaten','Tolikara');
insert into cities (`id`,`province_id`,`type`,`name`) values ('485','31','Kota','Tomohon');
insert into cities (`id`,`province_id`,`type`,`name`) values ('486','28','Kabupaten','Toraja Utara');
insert into cities (`id`,`province_id`,`type`,`name`) values ('487','11','Kabupaten','Trenggalek');
insert into cities (`id`,`province_id`,`type`,`name`) values ('488','19','Kota','Tual');
insert into cities (`id`,`province_id`,`type`,`name`) values ('489','11','Kabupaten','Tuban');
insert into cities (`id`,`province_id`,`type`,`name`) values ('490','18','Kabupaten','Tulang Bawang');
insert into cities (`id`,`province_id`,`type`,`name`) values ('491','18','Kabupaten','Tulang Bawang Barat');
insert into cities (`id`,`province_id`,`type`,`name`) values ('492','11','Kabupaten','Tulungagung');
insert into cities (`id`,`province_id`,`type`,`name`) values ('493','28','Kabupaten','Wajo');
insert into cities (`id`,`province_id`,`type`,`name`) values ('494','30','Kabupaten','Wakatobi');
insert into cities (`id`,`province_id`,`type`,`name`) values ('495','24','Kabupaten','Waropen');
insert into cities (`id`,`province_id`,`type`,`name`) values ('496','18','Kabupaten','Way Kanan');
insert into cities (`id`,`province_id`,`type`,`name`) values ('497','10','Kabupaten','Wonogiri');
insert into cities (`id`,`province_id`,`type`,`name`) values ('498','10','Kabupaten','Wonosobo');
insert into cities (`id`,`province_id`,`type`,`name`) values ('499','24','Kabupaten','Yahukimo');
insert into cities (`id`,`province_id`,`type`,`name`) values ('500','24','Kabupaten','Yalimo');
insert into cities (`id`,`province_id`,`type`,`name`) values ('501','5','Kota','Yogyakarta');